# Generated by Django 2.1.1 on 2018-09-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_quiz_times_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('i', 'In Progress'), ('r', 'In Review'), ('p', 'Published')], default='i', max_length=1),
        ),
    ]
